[env:esp32-s3-view]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters =
    esp32_exception_decoder
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    paulStoffregen/XPT2046_Touchscreen@^1.4
    digilect/JC_Button@^2.1.0
